name: Deploy-Develop

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - run: npm i --legacy-peer-deps
      - run: npm run build --if-present
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: dist/
          server: ftp.itysmexico.com.mx
          server-dir: /app.ltysmx.com/
          username: ltysmx@ltysmx.com
          password: 9Jj97YNkZ&r48jy50
